CREATE TABLE SETOR
(
 ID_SETOR BIGINT IDENTITY NOT NULL,
 DESCRICAO VARCHAR(35) NOT NULL,
 CONSTRAINT PK_SETOR PRIMARY KEY (ID_SETOR)
)

CREATE TABLE CARGO
(
 ID_CARGO BIGINT IDENTITY NOT NULL,
 DESCRICAO VARCHAR(35),
 CONSTRAINT PK_CARGO PRIMARY KEY (ID_CARGO)
)

CREATE TABLE FUNCIONARIO
(
 ID_FUNCIONARIO BIGINT IDENTITY NOT NULL,
 NOME VARCHAR(50) NOT NULL,
 SALARIO FLOAT NOT NULL,
 ID_SETOR BIGINT NOT NULL,
 ID_CARGO BIGINT NOT NULL,
 CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID_FUNCIONARIO)
)